baseURL = "/"
languageCode = "en-us"
title = "Diversity ∙ Supplementary Materials"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Anonymized"
    description = "Measuring the Growth of Diversity and Population Terminology in Biomedical Research"
    logo = "favicon/network-labels-new.png"
    accent = "#000000" # dark colors do best
    backgroundColor = "#ffffff"
    font = "Heebo" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/description/"
    name = "Project Description"
    weight = 2
    
[[menu.main]]
    url = "/analyses/"
    name = "Analyses"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://journals.sagepub.com/home/asr"
    name = "fas fa-book"
    weight = 1

[[menu.icon]]
    url = "https://github.com/brandonleekramer/diversity"
    name = "fab fa-github"
    weight = 2
    
[[menu.icon]]
    url = "mailto:brandonleekramer@gmail.com"
    name = "far fa-envelope"
    weight = 3
