baseURL = "/"
languageCode = "en-us"
title = "The Rise of Diversity and Population Terminology in Biomedical Research"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Anonymized for Review"
    description = ""
    logo = "favicon/network-labels-new.png"
    accent = "#000000" # dark colors do best
    backgroundColor = "#ffffff"
    font = "Heebo" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
#[[menu.main]]
#    url = "/overview/"
#    name = "Home"
#    weight = 1

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1
    
[[menu.main]]
    url = "/methods/"
    name = "Overview/Methods"
    weight = 2
    
[[menu.main]]
    url = "/results/"
    name = "Results"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

 [[menu.icon]]
    url = "https://journals.sagepub.com/home/asr"
    name = "fas fa-book"
    weight = 1

[[menu.icon]]
    url = "https://anonymous.4open.science/r/diversity-4EA7/README.md"
    name = "fab fa-github"
    weight = 2
    
#[[menu.icon]]
#    url = "mailto:"
#    name = "far fa-envelope"
#    weight = 3
