---
title: "Untitled"
author: "Brandon L. Kramer"
date: "11/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

general_pop_terms <- abstract_data %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(race|racial|racially)\\b"), 
                       yes = "racial*", no = word)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(ethnic|ethnicity|ethnically)\\b"), 
                       yes = "ethnic*", no = term)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(culture|cultural|culturally)\\b"), 
                       yes = "cultural*", no = term)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(population|populations)\\b"), 
                       yes = "population*", no = term)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern =
  "\\b(?i)(ancestry|ancestries|ancestral|ancestor|ancestors|descent|descendent|descendents)\\b"), 
                       yes = "ancestry*", no = term)) %>%
  count(id, term, sort = TRUE)

total_words <- abstract_words %>% 
  group_by(id) %>% 
  summarize(total = sum(n))

abstract_words <- left_join(abstract_words, total_words) %>% 
  rename(term = word)

abstract_words %>% 
  filter(term == "diversity" | term == "cultural*" | term == "genetic" | term == "population*" | 
         term == "racial*" | term == "ethnic*" | term == "ancestry*") 

freq_by_rank <- abstract_words %>% 
  group_by(id) %>% 
  mutate(rank = row_number(), 
         `term frequency` = n/total)

freq_by_rank %>% 
  filter(term == "diversity" | term == "cultural*" | term == "genetic" | term == "population*" | 
         term == "racial*" | term == "ethnic*" | term == "ancestry*")

freq_by_rank %>% 
  ggplot(aes(rank, `term frequency`, color = id)) + 
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()

freq_by_rank %>% 
  filter(term == "diversity" | term == "cultural*" | term == "genetic" | term == "population*" | 
         term == "racial*" | term == "ethnic*" | term == "ancestry*") %>% 
  ggplot(aes(rank, `term frequency`, color = id)) + 
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()

```

```{r}

plos one 
nature 
jama 
the lancet 
new england journal of medicine 
the bmj 
health affairs 
journal of internal medicine 
science 

```

```{r}
word_pairs <- text_data %>% 
  unnest_tokens(bigram, abstract, token = "ngrams", n = 2) 

word_cors <- austen_section_words %>%
  group_by(word) %>%
  filter(n() >= 20) %>%
  pairwise_cor(word, section, sort = TRUE)

word_cors
  
  
```