---
title: "Untitled"
author: "Brandon"
date: "8/18/2020"
output: html_document
---

```{r}
for (pkg in c("tidyverse", "igraph", "tidytext", "ggplot2", "DT", "udpipe", "word2vec",
              "grid", "gridExtra", "reshape2", "extrafont", "data.table", "maditr",
              "plotly", "stringi", "networkD3")) {library(pkg, character.only = TRUE)}

setwd("~/Documents/Diversity/Data")
# loading the .csv file 
biomed_text_data <- read_csv("biomedical_corpus.csv") %>% 
  rowid_to_column(var = "id") %>% 
  rename(authors = AU, title = TI, publication = SO, #author_keywords = DE,
         abstract = AB, references = CR, year = PY, times_cited = TC) %>% 
  select(id, authors, title, year, publication, abstract, references, year, times_cited) %>% 
  drop_na(abstract) %>% 
# filtering 2018 articles because they seem to be incomplete 
  filter(year != "2018") 
```

```{r}
x <- subset(biomed_text_data, year > 2009)
x <- tolower(x$abstract)
cat(x[1])

model <- word2vec(x = x, type = "cbow", dim = 15, iter = 20)

embedding <- as.matrix(model)
embedding <- predict(model, c("race", "racial", "ethnic", "ethnicity", 
                              "sex", "gender", "diverse", "diversity"), type = "embedding")
embedding

lookslike <- predict(model, c("race", "racial", "ethnic", "ethnicity", 
                              "sex", "gender", "diverse", "diversity"), type = "nearest", top_n = 50)

?word2vec
edgelist <- rbind(as.data.frame(lookslike$race),
      as.data.frame(lookslike$racial),
      as.data.frame(lookslike$ethnic),
      as.data.frame(lookslike$ethnicity),
      as.data.frame(lookslike$sex),
      as.data.frame(lookslike$gender),
      as.data.frame(lookslike$diverse),
      as.data.frame(lookslike$diversity))

# write_csv(edgelist, "test_edgelist.csv")
```

```{r}
y <- subset(biomed_text_data, year > 2015)
y <- tolower(y$abstract)
cat(y[1])

model2 <- word2vec(x = y, type = "cbow", dim = 15, iter = 20)

embedding2 <- as.matrix(model2)
embedding2 <- predict(model2, c("diversity", "race"), type = "embedding")
embedding2

lookslike2 <- predict(model2, c("diversity", "race", "ethnicity"), type = "nearest", top_n = 50)
lookslike2

```

```{r}
wv <- predict(model, newdata = c("black", "white", "sex", "gender"), type = "embedding")
wv <- wv["gender", ] - wv["black", ] + wv["white", ]
predict(model, newdata = wv, type = "nearest", top_n = 50)
```
```{r}
wv <- predict(model, newdata = c("black", "white", "sex", "gender"), type = "embedding")
wv <- wv["gender", ] - wv["white", ] + wv["black", ]
predict(model, newdata = wv, type = "nearest", top_n = 50)
```
















