---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library("tidyverse")

original <- read_csv("~/git/diversity/data/quality_check/diversity_qual_meaning_original.csv") %>% rename(abs_o = abstract)
julia_coded <- read_csv("~/git/diversity/data/quality_check/diversity_qual_meaning_julia.csv") %>% rename(abs_j = abstract)

joined_data <- cbind(original, julia_coded)

joined_data <- joined_data %>% 
  rename(julia_coded = Diversity, abstract = abs_j) %>% 
  select(abstract, julia_coded, diversity, term_total, everything(), -abs_o) %>% 
  arrange(-diversity) 
```


```{r}
comparison <- joined_data %>% 
  #select(-abstract) %>% 
  drop_na(julia_coded) %>% 
  arrange(julia_coded) %>% 
  mutate(true_diversity = if_else(diversity == 1 & term_total > 0, 1, 0),
         properly_coded = if_else((julia_coded == 1 & true_diversity == 1) | 
                                  (julia_coded == 0 & true_diversity == 0), 1, 0)) %>% 
  select(properly_coded, true_diversity,  everything()) %>% arrange(properly_coded)
write_csv(comparison, "~/git/diversity/data/quality_check/diversity_qual_meaning_comp.csv")
```



