---
title: "Untitled"
author: "Brandon L. Kramer"
date: "10/25/2019"
output: html_document
---

```{r setup, include = FALSE}
rm(list = ls())
knitr::opts_knit$set(root.dir = "~/Documents/Diversity/Data")
#knitr::opts_knit$set(root.dir = "C:/Users/bkram/CloudStation/Diversity/Data")
```
```{r load packages, message = FALSE, results = FALSE}
for (pkg in c("tidyverse", "igraph", "tidytext", "ggplot2", "ggraph", "widyr", "plotly", "stringi", "networkD3")) {library(pkg, character.only = TRUE)}
# loading the .csv file 
text_data <- read_csv("historical_text_data.csv") %>% 
# filtering 2018 articles because they seem to be incomplete 
  filter(year != "2018") 
# tokenizing the abstract data into words 
abstract_data <- text_data %>% 
  unnest_tokens(word, abstract) %>% 
  anti_join(stop_words)
# adding custom set of stopwords 
my_stopwords <- tibble(word = c(as.character(1:14), 
                                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
                                "rights", "reserved", "copyright", "elsevier"))
abstract_data <- abstract_data %>% anti_join(my_stopwords); rm(my_stopwords)
# most frequent word count in abstracts 
abstract_data %>%
  count(word, sort = TRUE)
```

```{r graphing the growth of diversity part ___, fig.width=9.5}
# recoding race*, ethnicity* and cultural* terminology
general_pop_terms <- abstract_data %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(race|racial|racially)\\b"), 
                       yes = "racial*", no = word)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(ethnic|ethnicity|ethnically)\\b"), 
                       yes = "ethnic*", no = term)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(culture|cultural|culturally)\\b"), 
                       yes = "cultural*", no = term)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(population|populations)\\b"), 
                       yes = "population*", no = term)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern =
  "\\b(?i)(ancestry|ancestries|ancestral|ancestor|ancestors|descent|descendent|descendents)\\b"), 
                       yes = "ancestry*", no = term)) %>% 
  
# grouping by year and filter relevant population terms 
  group_by(year) %>% count(term, sort = TRUE) %>% ungroup() %>% 
  filter(term == "diversity" | term == "cultural*" | term == "genetic" | term == "population*" | 
           term == "racial*" | term == "ethnic*" | term == "ancestry*") %>% 
# graphing terms over time 
  ggplot() + geom_line(aes(y = n, x = year, colour = term), stat="identity") + 
  labs(title = "Figure 2. Growth in General Diversity-Related Terms (1990-2017)") + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank(), 
        legend.title = element_blank()); ggplotly()
```


```{r}

general_pop_terms <- abstract_data %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(race|racial|racially)\\b"), 
                       yes = "racial*", no = word)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(ethnic|ethnicity|ethnically)\\b"), 
                       yes = "ethnic*", no = term)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(culture|cultural|culturally)\\b"), 
                       yes = "cultural*", no = term)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern = "\\b(?i)(population|populations)\\b"), 
                       yes = "population*", no = term)) %>% 
  mutate(term = ifelse(test = str_detect(string = abstract_data$word, 
                       pattern =
  "\\b(?i)(ancestry|ancestries|ancestral|ancestor|ancestors|descent|descendent|descendents)\\b"), 
                       yes = "ancestry*", no = term)) %>%
  count(id, term, sort = TRUE)

total_words <- abstract_words %>% 
  group_by(id) %>% 
  summarize(total = sum(n))

abstract_words <- left_join(abstract_words, total_words) %>% 
  rename(term = word)

abstract_words %>% 
  filter(term == "diversity" | term == "cultural*" | term == "genetic" | term == "population*" | 
         term == "racial*" | term == "ethnic*" | term == "ancestry*") 

freq_by_rank <- abstract_words %>% 
  group_by(id) %>% 
  mutate(rank = row_number(), 
         `term frequency` = n/total)

freq_by_rank %>% 
  filter(term == "diversity" | term == "cultural*" | term == "genetic" | term == "population*" | 
         term == "racial*" | term == "ethnic*" | term == "ancestry*")

freq_by_rank %>% 
  ggplot(aes(rank, `term frequency`, color = id)) + 
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()

freq_by_rank %>% 
  filter(term == "diversity" | term == "cultural*" | term == "genetic" | term == "population*" | 
         term == "racial*" | term == "ethnic*" | term == "ancestry*") %>% 
  ggplot(aes(rank, `term frequency`, color = id)) + 
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()

```

```{r}

plos one 
nature 
jama 
the lancet 
new england journal of medicine 
the bmj 
health affairs 
journal of internal medicine 
science 

```









