---
title: "Topic Modeling"
author: "Brandon L. Kramer"
date: "1/17/2020"
output: html_document
---

```{r setup, include = FALSE}
rm(list = ls())
#knitr::opts_knit$set(root.dir = "~/Documents/Diversity/Data")
knitr::opts_knit$set(root.dir = "C:/Users/bkram/CloudStation/Diversity/Data")
```

```{r load packages, message = FALSE, results = FALSE, echo=FALSE}
# loading packages 
for (pkg in c("tidyverse", "igraph", "tidytext", "ggplot2", "topicmodels", "tm", "ldatuning",
              "ggraph", "widyr", "plotly", "stringi", "networkD3")) {library(pkg, character.only = TRUE)}
# loading the .csv file 
text_data <- read_csv("diversity_corpus.csv") %>% 
# filtering 2018 articles because they seem to be incomplete 
  filter(year != "2018") 

test_data <- text_data %>% 
  slice(1:3000)

```

```{r}

by_abstract <- test_data %>% 
  unnest_tokens(word, abstract)

my_stopwords <- tibble(word = c(as.character(1:14), 
                                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
                                "rights", "reserved", "copyright", "elsevier"))

word_counts <- by_abstract %>% 
  anti_join(stop_words) %>% 
  anti_join(my_stopwords) %>% 
  count(publication, word, sort = TRUE)
  
word_counts

pubs_dtm <- word_counts %>%
  cast_dtm(publication, word, n)

```

```{r}

finding_k <- FindTopicsNumber(
  pubs_dtm,
  topics = seq(from = 10, to = 150, by = 10),
  metrics = c("Griffiths2004", "CaoJuan2009", "Arun2010", "Deveaud2014"),
  method = "Gibbs",
  control = list(seed = 77),
  #mc.cores = 2L, # defaults to NA and finds cores available 
  verbose = TRUE)

FindTopicsNumber_plot(finding_k)

?FindTopicsNumber

```


```{r, fig.width=11.5}

pubs_lda <- LDA(pubs_dtm, k = 10, control = list(seed = 1234))

pubs_lda_td <- tidy(pubs_lda)
pubs_lda_td

top_terms <- pubs_lda_td %>%
  group_by(topic) %>%
  top_n(5, beta) %>%
  ungroup() %>%
  arrange(topic, -beta)

top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(term, beta)) +
  geom_bar(stat = "identity") +
  scale_x_reordered() +
  facet_wrap(~ topic, scales = "free_x")

```






Citations 

https://cran.r-project.org/web/packages/tidytext/vignettes/topic_modeling.html

https://cran.r-project.org/web/packages/ldatuning/vignettes/topics.html 

https://rpubs.com/MNidhi/NumberoftopicsLDA

































